project_name: "aws-iam-user"

# before are hooks that will be run before any builds are done, so good to put install scripts and stuff that your builds need here
before:
  hooks:
    # Remove unused packaged from the build process
    - go mod tidy
    - go generate

signs:
  - artifacts: all
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

builds:
  - main: ./main.go
    binary: aws-iam-user
    goos: ["linux", "darwin", "windows"]
    goarch: ["386", "amd64", "arm64"]
    env:
      - CGO_ENABLED=0

nfpms:
  - package_name: aws-iam-user
    homepage: https://github.com/conijnio/aws-iam-user/
    maintainer: Joris Conijn <joris@conijnonline.nl>
    description: |-
      Template for golang projects
    formats:
      - rpm
      - deb

sboms:
  - artifacts: archive

brews:
  - repository:
      owner: conijnio
      name: homebrew-aws-iam-user
    name: aws-iam-user
    homepage: https://github.com/conijnio/aws-iam-user
    description: Manage your IAM credentials easily.
    license: Apache License 2.0
    skip_upload: auto
    commit_author:
      name: Joris Conijn
      email: joris@conijnonline.nl
    folder: Formula
    install: |-
      bin.install "aws-iam-user"
    test: |
      system "#{bin}/aws-iam-user -v"

changelog:
  sort: "asc"
  filters:
    exclude: ["^docs:", "demo", "^hugo:", "Merge pull request", "Merge branch"]
